on:
  workflow_dispatch:

name: "Build executable"

jobs:
  build:
    name: Build
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-qjsc
        with:
          path: soft/quickjs-2020-11-08
          key: ${{ runner.os }}-quickjs-3

      - uses: actions/cache@v2
        id: cache-tush
        with:
          path: soft/tush
          key: ${{ runner.os }}-tush-2

      - name: "build & run tests"
        run: |
          ./makesure

      - uses: actions/upload-artifact@v2
        with:
          name: jsqry-macos
          path: build/jsqry
