on: ["push", "pull_request"]

name: "Build and test"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - uses: actions/cache@v2
#        id: cache-qjsc
#        with:
#          path: path/to/dependencies

      - name: "download & extract & compile qjsc"
        run: |
          QJS=quickjs-2020-07-05
          wget https://bellard.org/quickjs/$QJS.tar.xz
          tar xvf ./$QJS.tar.xz
          mv $QJS quickjs

          echo
          echo "Compile"
          echo

          cd quickjs
          make qjsc libquickjs.a

      - name: "build jsqry"
        run: |
          mkdir build
          cd build
          ../quickjs/qjsc ../jsqry-cli.js -o jsqry

      - name: "prepare test tool"
        run: |
          wget https://github.com/adolfopa/tush/archive/master.zip -O./tush.zip
          unzip ./tush.zip

      - name: "run tests"
        run: |
          export PATH=$(cd ./tush-master/bin; pwd):$PATH
          echo "PATH=$PATH"
          ./tests.sh
