on: ["push", "pull_request"]

name: "Build and test"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "download qjsc" # TODO cache
        run: |
          echo "quickjs-2020-07-05" > .qjsf
          wget https://bellard.org/quickjs/$(cat .qjsf).tar.xz

      - name: "extract quickjs"
        run: |
          tar xvf ./$(cat .qjsf).tar.xz

      - name: "compile qjsc"
        run: |
          cd $(cat .qjsf)
          make qjsc libquickjs.a

      - name: "build jsqry"
        run: |
          mkdir build
          cd build
          ../$(cat ../.qjsf)/qjsc ../jsqry-cli.js -o jsqry

      - name: "prepare test tool"
        run: |
          wget https://github.com/adolfopa/tush/archive/master.zip -O./tush.zip
          unzip ./tush.zip

      - name: "run tests"
        run: |
          export PATH=$(cd ./tush-master/bin; pwd):$PATH
          echo "PATH=$PATH"
          ./tests.sh


