on: [ "push", "pull_request" ]

name: "Build and test"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-qjsc
        with:
          path: soft/quickjs-2020-11-08
          key: quickjs-3

      - uses: actions/cache@v2
        id: cache-tush
        with:
          path: soft/tush
          key: tush-2

      - name: "build & run tests"
        run: |
          TESTONLY=1 ./build.sh
