on: [ "push", "pull_request" ]

name: "Build and test"

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-qjsc
        with:
          path: soft/quickjs-2020-11-08
          key: ${{ runner.os }}-quickjs-3

      - uses: actions/cache@v2
        id: cache-tush
        with:
          path: soft/tush
          key: ${{ runner.os }}-tush-2

      - name: "build & run tests"
        run: |
          ./makesure tested
